#!/usr/bin/env bash
# build.sh  —  Full Vibechecker Windows build pipeline (runs in Git Bash)
#
# Prerequisites:
#   - 64-bit Python 3.10+ in PATH
#   - pip install pyinstaller
#   - PicoSDK installed (for DLL collection step)
#   - Inno Setup 6.x installed
#
# Usage:
#   ./build.sh              # full build: DLLs + PyInstaller + Inno Setup
#   ./build.sh dlls         # DLL collection only
#   ./build.sh pyinstaller  # PyInstaller only (skip DLL collection)
#   ./build.sh installer    # Inno Setup only (requires dist/ to exist)

set -euo pipefail

STEP="${1:-all}"

# Locate iscc.exe — try PATH first, then common install locations.
# $LOCALAPPDATA is a Windows-style path in Git Bash; convert with cygpath.
find_iscc() {
    if command -v iscc &>/dev/null; then
        echo "iscc"
        return
    fi
    local localappdata_unix=""
    if [[ -n "${LOCALAPPDATA:-}" ]]; then
        localappdata_unix=$(cygpath "$LOCALAPPDATA" 2>/dev/null || echo "")
    fi
    local candidates=(
        "$localappdata_unix/Programs/Inno Setup 6/iscc.exe"
        "/c/Program Files (x86)/Inno Setup 6/iscc.exe"
        "/c/Program Files/Inno Setup 6/iscc.exe"
    )
    for c in "${candidates[@]}"; do
        if [[ -n "$c" && -f "$c" ]]; then
            echo "$c"
            return
        fi
    done
    echo ""
}

echo
echo "============================================================"
echo "  Vibechecker Windows Build Pipeline"
echo "============================================================"
echo

# ── Preflight checks ─────────────────────────────────────────────────────────
if [[ "$STEP" == "all" || "$STEP" == "installer" ]]; then
    ISCC="$(find_iscc)"
    if [[ -z "$ISCC" ]]; then
        echo "ERROR: iscc.exe not found. Install Inno Setup 6 from https://jrsoftware.org/isinfo.php"
        exit 1
    fi
    echo "Found Inno Setup: $ISCC"
    echo
fi

# ── Step 1: Stamp version ────────────────────────────────────────────────────
# Always runs so the frozen binary embeds the correct tag, even if the
# pre-commit hook wrote a stale value (e.g. after a manual tag was applied).
VERSION=$(git describe --tags --always 2>/dev/null || echo "dev")
printf '# Auto-generated by build.sh — do not edit\n__version__ = "%s"\n' "$VERSION" \
    > vibechecker/_version.py
echo "Version: $VERSION"
echo

# ── Step 2: Collect PicoScope DLLs ──────────────────────────────────────────
if [[ "$STEP" == "all" || "$STEP" == "dlls" ]]; then
    echo "[2/4] Collecting PicoScope DLLs..."
    python build/collect_pico_dlls.py
    echo
fi

# ── Step 3: PyInstaller ──────────────────────────────────────────────────────
if [[ "$STEP" == "all" || "$STEP" == "pyinstaller" ]]; then
    echo "[3/4] Building executable with PyInstaller..."

    # Kill any running instance so Windows releases file locks on output DLLs
    taskkill /f /im vibechecker.exe >/dev/null 2>&1 || true

    # Wipe previous output cleanly — pyinstaller --noconfirm skips locked files
    if [[ -d dist/vibechecker ]]; then
        echo "Cleaning previous build output..."
        rm -rf dist/vibechecker
    fi

    python -m PyInstaller vibechecker.spec --noconfirm --clean
    echo
fi

# ── Step 4: Inno Setup ───────────────────────────────────────────────────────
if [[ "$STEP" == "all" || "$STEP" == "installer" ]]; then
    echo "[4/4] Creating installer with Inno Setup..."
    "$ISCC" installer/vibechecker.iss
    echo
fi

echo "============================================================"
echo "  Build complete."
echo "  Installer: installer/Output/VibecheckerSetup-*.exe"
echo "============================================================"
