#!/usr/bin/env bash
# build.sh  —  Full Rev80 Windows build pipeline (runs in Git Bash)
#
# Prerequisites:
#   - 64-bit Python 3.10+ in PATH
#   - pip install pyinstaller
#   - PicoSDK DLLs available via one of:
#       a) PicoSDK installed on the build machine (auto-detected via registry)
#       b) PICO_DLL_DIR env var pointing at a directory with ps4000a.dll + picoipp.dll
#       c) vendor/pico/ in project root (gitignored) containing the same DLLs
#      Source: C:\Program Files\Pico Technology\SDK\lib\ on any PicoSDK install
#   - Inno Setup 6.x installed
#
# Usage:
#   ./build.sh              # full build: DLLs + PyInstaller + Inno Setup
#   ./build.sh dlls         # DLL collection only
#   ./build.sh pyinstaller  # PyInstaller only (skip DLL collection)
#   ./build.sh installer    # Inno Setup only (requires dist/ to exist)

set -euo pipefail

STEP="${1:-all}"
# Pass --clean to force a full PyInstaller cache wipe (slow but safe after
# adding new dependencies or if the build cache seems corrupt):
#   ./build.sh all clean
PYINSTALLER_CLEAN=""
for arg in "$@"; do
    [[ "$arg" == "clean" ]] && PYINSTALLER_CLEAN="--clean"
done

# Locate iscc.exe — try PATH first, then common install locations.
# $LOCALAPPDATA is a Windows-style path in Git Bash; convert with cygpath.
find_iscc() {
    if command -v iscc &>/dev/null; then
        echo "iscc"
        return
    fi
    local localappdata_unix=""
    if [[ -n "${LOCALAPPDATA:-}" ]]; then
        localappdata_unix=$(cygpath "$LOCALAPPDATA" 2>/dev/null || echo "")
    fi
    local candidates=(
        "$localappdata_unix/Programs/Inno Setup 6/iscc.exe"
        "/c/Program Files (x86)/Inno Setup 6/iscc.exe"
        "/c/Program Files/Inno Setup 6/iscc.exe"
    )
    for c in "${candidates[@]}"; do
        if [[ -n "$c" && -f "$c" ]]; then
            echo "$c"
            return
        fi
    done
    echo ""
}

echo
echo "============================================================"
echo "  Rev80 Windows Build Pipeline"
echo "============================================================"
echo

# ── Preflight checks ─────────────────────────────────────────────────────────
if [[ "$STEP" == "all" || "$STEP" == "installer" ]]; then
    ISCC="$(find_iscc)"
    if [[ -z "$ISCC" ]]; then
        echo "ERROR: iscc.exe not found. Install Inno Setup 6 from https://jrsoftware.org/isinfo.php"
        exit 1
    fi
    echo "Found Inno Setup: $ISCC"
    echo
fi

# ── Step 1: Fetch font ───────────────────────────────────────────────────────
./scripts/fetch_font.sh
## Font is gitignored; download on first build and cache locally.
#FONT_FILE="assets/fonts/CommitMonoNerdFont-Regular.otf"
#FONT_URL="https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/CommitMono.zip"
#if [[ ! -f "$FONT_FILE" ]]; then
#    echo "[1/5] Downloading CommitMono Nerd Font..."
#    mkdir -p assets/fonts
#    TMP_ZIP=$(mktemp /tmp/CommitMono.XXXXXX.zip)
#    curl -L --fail --progress-bar "$FONT_URL" -o "$TMP_ZIP"
#    unzip -j "$TMP_ZIP" "CommitMonoNerdFont-Regular.otf" -d assets/fonts/
#    rm "$TMP_ZIP"
#    echo
#else
#    echo "[1/5] Font already present — skipping download."
#    echo
#fi

# ── Step 2: Refresh version ──────────────────────────────────────────────────
# src/rev80/_version.py is generated by setuptools_scm from the current git
# state (tags, describe) whenever the local package is (re)installed — a
# quick --no-deps reinstall regenerates it fresh here so the frozen binary
# always embeds the correct tag, even if it's been a while since the last
# `pip install -e .` (e.g. a tag was applied after that).

echo "[2/5] Reinstall package with pip."
#echo "Activate venv..."
#source .venv/Scripts/activate # user must activate their venv.
echo "pip install -e . -q" 
pip install -e . -q --no-deps
VERSION=$(python -c "import rev80; print(rev80.__version__)")
echo "Version: $VERSION"
echo

# ── Step 3: Collect PicoScope DLLs ──────────────────────────────────────────
if [[ "$STEP" == "all" || "$STEP" == "dlls" ]]; then
    echo "[3/5] Collecting PicoScope DLLs..."
    python build/collect_pico_dlls.py
    echo
fi

# ── Step 4: PyInstaller ──────────────────────────────────────────────────────
if [[ "$STEP" == "all" || "$STEP" == "pyinstaller" ]]; then
    echo "[4/5] Building executable with PyInstaller..."

    # Kill any running instance so Windows releases file locks on output DLLs
    taskkill /f /im rev80.exe >/dev/null 2>&1 || true

    # Wipe previous output cleanly — pyinstaller --noconfirm skips locked files
    if [[ -d dist/rev80 ]]; then
        echo "Cleaning previous build output..."
        rm -rf dist/rev80
    fi

    python -m PyInstaller build/rev80.spec --noconfirm $PYINSTALLER_CLEAN
    echo
fi

# ── Step 5: Inno Setup ───────────────────────────────────────────────────────
if [[ "$STEP" == "all" || "$STEP" == "installer" ]]; then
    echo "[5/5] Creating installer with Inno Setup..."
    "$ISCC" installer/rev80.iss
    echo
fi

echo "============================================================"
echo "  Build complete."
echo "  Installer: installer/Output/Rev80Setup-*.exe"
echo "============================================================"
